## Timedelta objects

In [1]:
#timedelta is the difference between the two dates and the time

In [2]:
import pandas as pd
import numpy as np

In [3]:
t1=pd.Timestamp("6th jan 2023")
t2=pd.Timestamp("9th jan 2023")
t2-t1

Timedelta('3 days 00:00:00')

In [4]:
t1-t2

Timedelta('-3 days +00:00:00')

In [5]:
#here t1-t2 is simply a time delta

In [6]:
#also we can directly create the time delta objects

In [7]:
pd.Timedelta(days=2,hours=3,minutes=35)

Timedelta('2 days 03:35:00')

In [8]:
# Arithmetic
pd.Timestamp('6th jan 2023') + pd.Timedelta(days=2,hours=10,minutes=35)

Timestamp('2023-01-08 10:35:00')

In [9]:
pd.date_range(start='2023-1-6',end='2023-1-31',freq='D') + pd.Timedelta(days=2,hours=10,minutes=35)

DatetimeIndex(['2023-01-08 10:35:00', '2023-01-09 10:35:00',
               '2023-01-10 10:35:00', '2023-01-11 10:35:00',
               '2023-01-12 10:35:00', '2023-01-13 10:35:00',
               '2023-01-14 10:35:00', '2023-01-15 10:35:00',
               '2023-01-16 10:35:00', '2023-01-17 10:35:00',
               '2023-01-18 10:35:00', '2023-01-19 10:35:00',
               '2023-01-20 10:35:00', '2023-01-21 10:35:00',
               '2023-01-22 10:35:00', '2023-01-23 10:35:00',
               '2023-01-24 10:35:00', '2023-01-25 10:35:00',
               '2023-01-26 10:35:00', '2023-01-27 10:35:00',
               '2023-01-28 10:35:00', '2023-01-29 10:35:00',
               '2023-01-30 10:35:00', '2023-01-31 10:35:00',
               '2023-02-01 10:35:00', '2023-02-02 10:35:00'],
              dtype='datetime64[ns]', freq='D')

In [10]:
pd.date_range(start='2023-1-6',end='2023-1-31',freq='D') - pd.Timedelta(days=2,hours=10,minutes=35)

DatetimeIndex(['2023-01-03 13:25:00', '2023-01-04 13:25:00',
               '2023-01-05 13:25:00', '2023-01-06 13:25:00',
               '2023-01-07 13:25:00', '2023-01-08 13:25:00',
               '2023-01-09 13:25:00', '2023-01-10 13:25:00',
               '2023-01-11 13:25:00', '2023-01-12 13:25:00',
               '2023-01-13 13:25:00', '2023-01-14 13:25:00',
               '2023-01-15 13:25:00', '2023-01-16 13:25:00',
               '2023-01-17 13:25:00', '2023-01-18 13:25:00',
               '2023-01-19 13:25:00', '2023-01-20 13:25:00',
               '2023-01-21 13:25:00', '2023-01-22 13:25:00',
               '2023-01-23 13:25:00', '2023-01-24 13:25:00',
               '2023-01-25 13:25:00', '2023-01-26 13:25:00',
               '2023-01-27 13:25:00', '2023-01-28 13:25:00'],
              dtype='datetime64[ns]', freq='D')

### Time series

A time series is a data set that tracks a sample over time. In particular, a time series allows one to see what factors influence certain variables from period to period. Time series analysis can be useful to see how a given asset, security, or economic variable changes over time.

Examples

- Financial Data (Company stocks)
- Natural Data (Rainfall measurement)
- Event Data (Covid)
- Medical Data (Heart rate monitoring)

Types of Operations done on Time Series

- Time Series Analysis
- Time Series Forecasting

In [11]:
google=pd.read_csv("time series analysis datasets/google.csv")

In [12]:
google.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  2004-08-19  49.813290  51.835709  47.800831  49.982655  49.982655  44871361
1  2004-08-20  50.316402  54.336334  50.062355  53.952770  53.952770  22942874
2  2004-08-23  55.168217  56.528118  54.321388  54.495735  54.495735  18342897
3  2004-08-24  55.412300  55.591629  51.591621  52.239197  52.239197  15319808
4  2004-08-25  52.284027  53.798351  51.746044  52.802086  52.802086   9232276

In [13]:
google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4471 entries, 0 to 4470
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4471 non-null   object
 1   Open       4471 non-null   float64
 2   High       4471 non-null   float64
 3   Low        4471 non-null   float64
 4   Close      4471 non-null   float64
 5   Adj Close  4471 non-null   float64
 6   Volume     4471 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 244.6+ KB

In [14]:
google["Date"]=pd.to_datetime(google["Date"])

In [15]:
google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4471 entries, 0 to 4470
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4471 non-null   datetime64[ns]
 1   Open       4471 non-null   float64
 2   High       4471 non-null   float64
 3   Low        4471 non-null   float64
 4   Close      4471 non-null   float64
 5   Adj Close  4471 non-null   float64
 6   Volume     4471 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 244.6 KB

In [16]:
google.set_index("Date",inplace=True)

In [17]:
google.loc["2021-10-12"]

Open         2.792750e+03
High         2.793900e+03
Low          2.725000e+03
Close        2.734260e+03
Adj Close    2.734260e+03
Volume       1.126800e+06
Name: 2021-10-12 00:00:00, dtype: float64

In [18]:
google.loc["2021-11"]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-11-01,2963.300049,2967.989990,2871.590088,2875.479980,2875.479980,1613600
2021-11-02,2896.187988,2938.409912,2892.820068,2917.260010,2917.260010,1057500
2021-11-03,2925.500000,2938.209961,2901.070068,2935.800049,2935.800049,894300
2021-11-04,2944.000000,2999.000000,2932.699951,2973.659912,2973.659912,1235000
2021-11-05,2987.070068,3011.415039,2973.040039,2984.820068,2984.820068,1020400
2021-11-08,3000.000000,3020.689941,2982.399902,2987.030029,2987.030029,919400
2021-11-09,2994.919922,3007.570068,2950.139893,2984.969971,2984.969971,843800
2021-11-10,2960.195068,2974.000000,2906.500000,2932.520020,2932.520020,1135400
2021-11-11,2942.139893,2970.044922,2933.889893,2934.959961,2934.959961,623200
2021-11-12,2956.629883,2997.189941,2929.080078,2992.909912,2992.909912,852400
2021-11-15,3000.000000,3009.540039,2973.050049,2987.760010,2987.760010,812400
2021-11-16,2983.409912,2996.649902,2967.000000,2981.520020,2981.520020,862700
2021-11-17,2984.580078,2992.520020,2971.260010,2981.239990,2981.239990,764500
2021-11-18,2982.919922,3032.199951,2979.969971,3014.179932,3014.179932,1332900
2021-11-19,3020.000000,3037.000000,2997.750000,2999.050049,2999.050049,988300
2021-11-22,3002.834961,3014.889893,2940.110107,2941.570068,2941.570068,1230400
2021-11-23,2942.260010,2953.879883,2897.790039,2935.139893,2935.139893,906300
2021-11-24,2927.000000,2940.000000,2903.979980,2934.350098,2934.350098,823200
2021-11-26,2900.310059,2905.939941,2849.709961,2856.120117,2856.120117,849600
2021-11-29,2885.969971,2937.239990,2885.969971,2922.280029,2922.280029,1313800
2021-11-30,2909.004883,2932.570068,2841.320068,2849.040039,2849.040039,2079500

In [19]:
google.loc["2021"]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-01-04,1757.540039,1760.650024,1707.849976,1728.239990,1728.239990,1901900
2021-01-05,1725.000000,1747.670044,1718.015015,1740.920044,1740.920044,1145300
2021-01-06,1702.630005,1748.000000,1699.000000,1735.290039,1735.290039,2602100
2021-01-07,1740.060059,1788.400024,1737.050049,1787.250000,1787.250000,2265000
2021-01-08,1787.979980,1809.839966,1773.535034,1807.209961,1807.209961,2050600
...,...,...,...,...,...,...
2021-12-27,2949.270020,2968.530029,2945.000000,2961.280029,2961.280029,662800
2021-12-28,2967.489990,2967.489990,2918.709961,2928.959961,2928.959961,931200
2021-12-29,2928.590088,2943.675049,2910.090088,2930.090088,2930.090088,851100
2021-12-30,2929.000000,2941.250000,2915.169922,2920.050049,2920.050049,648900
2021-12-31,2910.879883,2927.300049,2893.550049,2893.590088,2893.590088,864900

In [20]:
google['month_name'] = google.index.month_name()
google['weekday_name'] = google.index.day_name()
google['quarter'] = google.index.quarter

google.head()

,Open,High,Low,Close,Adj Close,Volume,month_name,weekday_name,quarter
Date,,,,,,,,,
2004-08-19,49.813290,51.835709,47.800831,49.982655,49.982655,44871361,August,Thursday,3
2004-08-20,50.316402,54.336334,50.062355,53.952770,53.952770,22942874,August,Friday,3
2004-08-23,55.168217,56.528118,54.321388,54.495735,54.495735,18342897,August,Monday,3
2004-08-24,55.412300,55.591629,51.591621,52.239197,52.239197,15319808,August,Tuesday,3
2004-08-25,52.284027,53.798351,51.746044,52.802086,52.802086,9232276,August,Wednesday,3