In [1]:
import numpy as np
import pandas as pd

In [2]:
# vectorized operation: operate on any vector

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a*4

array([ 4,  8, 12, 16])

In [5]:
# problem in vectorized opertions in vanilla python
#s = ['cat','mat',None,'rat']

#[i.startswith('c') for i in s]
# not working for a none type data

In [6]:
s=pd.Series(["cat","dog",None ,"rat"])
s

0     cat
1     dog
2    None
3     rat
dtype: object

In [7]:
s.str.startswith("c")

0     True
1    False
2     None
3    False
dtype: object

In [8]:
df=pd.read_csv("./session22datasets/titanic.csv")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## lower

In [9]:
df["Name"].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

## upper()

In [10]:
df["Name"].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

## capitalize()

In [11]:
df["Name"].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [12]:
df["Name"].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [13]:
df[df["Name"].str.len()==82]["Name"]

307    Penasco y Castellana, Mrs. Victor de Satode (M...
Name: Name, dtype: object

In [14]:
df["Name"][df["Name"].str.len()==82]

307    Penasco y Castellana, Mrs. Victor de Satode (M...
Name: Name, dtype: object

## strip()

In [15]:
"       ananda          ".strip()

'ananda'

In [16]:
df["Name"].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

## split()

In [17]:
df["Name"].str.split(",")

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

## get ()

In [18]:
df["Name"].str.split(",").str.get(0)

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [19]:
df["Name"].str.split(",").str.get(1)

0                                  Mr. Owen Harris
1       Mrs. John Bradley (Florence Briggs Thayer)
2                                      Miss. Laina
3               Mrs. Jacques Heath (Lily May Peel)
4                                Mr. William Henry
                          ...
886                                    Rev. Juozas
887                           Miss. Margaret Edith
888                 Miss. Catherine Helen "Carrie"
889                                Mr. Karl Howell
890                                    Mr. Patrick
Name: Name, Length: 891, dtype: object

In [20]:
df["Name"].str.split(",").str.get(2)

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
886   NaN
887   NaN
888   NaN
889   NaN
890   NaN
Name: Name, Length: 891, dtype: float64

In [21]:
# now use this vectorized string operation make a seprate first name and last name of the poeple in a dataframe

In [22]:
df["firstname"]=df["Name"].str.split(",").str.get(1)

In [23]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr. Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs. John Bradley (Florence Briggs Thayer)

In [24]:
df["surename"]=df["Name"].str.split(",").str.get(0)

In [25]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,firstname,surename
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S,Mr. Owen Harris,Braund

## space related problems

In [26]:
df["Name"].str.split(",")
# now a name is splited according to the comma

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [27]:
# now only take the first name 
df["Name"].str.split(",").str.get(1)
# now we have a first name only

0                                  Mr. Owen Harris
1       Mrs. John Bradley (Florence Briggs Thayer)
2                                      Miss. Laina
3               Mrs. Jacques Heath (Lily May Peel)
4                                Mr. William Henry
                          ...
886                                    Rev. Juozas
887                           Miss. Margaret Edith
888                 Miss. Catherine Helen "Carrie"
889                                Mr. Karl Howell
890                                    Mr. Patrick
Name: Name, Length: 891, dtype: object

In [28]:
df["Name"].str.split(",").str.get(1).str.split(" ")
# now its seprate from all the presented space

0                                  [, Mr., Owen, Harris]
1      [, Mrs., John, Bradley, (Florence, Briggs, Tha...
2                                       [, Miss., Laina]
3            [, Mrs., Jacques, Heath, (Lily, May, Peel)]
4                                [, Mr., William, Henry]
                             ...
886                                     [, Rev., Juozas]
887                           [, Miss., Margaret, Edith]
888                [, Miss., Catherine, Helen, "Carrie"]
889                                [, Mr., Karl, Howell]
890                                     [, Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [29]:
# but i want to seprate only the mr and others name 
df["Name"].str.split(",").str.get(1).str.split(" ",n=1)

0                                 [, Mr. Owen Harris]
1      [, Mrs. John Bradley (Florence Briggs Thayer)]
2                                     [, Miss. Laina]
3              [, Mrs. Jacques Heath (Lily May Peel)]
4                               [, Mr. William Henry]
                            ...
886                                   [, Rev. Juozas]
887                          [, Miss. Margaret Edith]
888                [, Miss. Catherine Helen "Carrie"]
889                               [, Mr. Karl Howell]
890                                   [, Mr. Patrick]
Name: Name, Length: 891, dtype: object

## it gives me the ambuguty results because here blank space presents in the data so we have to remove the blank space first and then split according 
##  to the space

In [30]:
df["Name"].str.split(",").str.get(1).str.strip().str.split(" ")

0                                    [Mr., Owen, Harris]
1      [Mrs., John, Bradley, (Florence, Briggs, Thayer)]
2                                         [Miss., Laina]
3              [Mrs., Jacques, Heath, (Lily, May, Peel)]
4                                  [Mr., William, Henry]
                             ...
886                                       [Rev., Juozas]
887                             [Miss., Margaret, Edith]
888                  [Miss., Catherine, Helen, "Carrie"]
889                                  [Mr., Karl, Howell]
890                                       [Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [31]:
df["Name"].str.split(",").str.get(1).str.strip().str.split(" ",n=1)

0                                 [Mr., Owen Harris]
1      [Mrs., John Bradley (Florence Briggs Thayer)]
2                                     [Miss., Laina]
3              [Mrs., Jacques Heath (Lily May Peel)]
4                               [Mr., William Henry]
                           ...
886                                   [Rev., Juozas]
887                          [Miss., Margaret Edith]
888                [Miss., Catherine Helen "Carrie"]
889                               [Mr., Karl Howell]
890                                   [Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [32]:
df["Name"].str.split(",").str.get(1).str.strip().str.split(" ",n=2)

0                                 [Mr., Owen, Harris]
1      [Mrs., John, Bradley (Florence Briggs Thayer)]
2                                      [Miss., Laina]
3              [Mrs., Jacques, Heath (Lily May Peel)]
4                               [Mr., William, Henry]
                            ...
886                                    [Rev., Juozas]
887                          [Miss., Margaret, Edith]
888                [Miss., Catherine, Helen "Carrie"]
889                               [Mr., Karl, Howell]
890                                    [Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [33]:
# n=1 is required form which sperate the mr,mrs and name of the people

## expand=True

In [34]:
df["Name"].str.split(",").str.get(1).str.strip().str.split(" ",n=2,expand=True)
# convert into the dataframe

         0          1                                 2
0      Mr.       Owen                            Harris
1     Mrs.       John  Bradley (Florence Briggs Thayer)
2    Miss.      Laina                              None
3     Mrs.    Jacques             Heath (Lily May Peel)
4      Mr.    William                             Henry
..     ...        ...                               ...
886   Rev.     Juozas                              None
887  Miss.   Margaret                             Edith
888  Miss.  Catherine                    Helen "Carrie"
889    Mr.       Karl                            Howell
890    Mr.    Patrick                              None

[891 rows x 3 columns]

In [35]:
df[['title','firstname']] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ', n=1, expand=True)
df.head()

df['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Col.           2
Mlle.          2
Major.         2
Ms.            1
Mme.           1
Don.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [36]:
# replace
df['title'] = df['title'].str.replace('Ms.','Miss.')
df['title'] = df['title'].str.replace('Mlle.','Miss.')

In [37]:
df["title"].value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Lady.          1
Mme.           1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [39]:
# filtering
# startswith/endswith
df[df['firstname'].str.endswith('A')]
# isdigit/isalpha...
df[df['firstname'].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, firstname, surename, title]
Index: []

In [49]:
# lets find the name of the passenger whose first name is john 
df[df["surename"].str.contains("john",case=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,firstname,surename,title
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Oscar W (Elisabeth Vilhelmina Berg),Johnson,Mrs.
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,11.1333,NaN,S,Eleanor Ileen,Johnson,Miss.
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,NaN,S,William Cahoone Jr,Johnson,Mr.
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0000,NaN,S,Alfred,Johnson,Mr.
719,720,0,3,"Johnson, Mr. Malkolm Joackim",male,33.0,0,0,347062,7.7750,NaN,S,Malkolm Joackim,Johnson,Mr.
783,784,0,3,"Johnston, Mr. Andrew G",male,NaN,1,2,W./C. 6607,23.4500,NaN,S,Andrew G,Johnston,Mr.
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,Harold Theodor,Johnson,Master.
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"Catherine Helen ""Carrie""",Johnston,Miss.

## regular expression

In [52]:
# find the last name of the person whose surename start with the vowel letter and end with the vowel letter
df[df["surename"].str.contains("^[aeiouAEIOU].+[aeiouAEIOU]$")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,firstname,surename,title
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Manuel E,Uruchurtu,Don.
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,Josef (Josefine Franchi),Arnold-Franchi,Mrs.
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,Nassef Cassem,Albimona,Mr.
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Ahmed,Ali,Mr.
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,NaN,S,Josef,Arnold-Franchi,Mr.
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,Ramon,Artagaveytia,Mr.
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S,"William A (Florence ""Mary"" Agnes Hughes)",Angle,Mrs.
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,William,Ali,Mr.
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,Ilmari Rudolf,Alhomaki,Mr.

## slicing

In [58]:
df["Name"].str[::2]

0                    Ban,M.Oe ars
1      Cmns r.Jh rde Foec rgsTae)
2                     Hiknn is an
3          Ftel,Ms aqe et Ll a el
4                    Aln r ila er
                  ...
886                   Mnvl,Rv uzs
887                Gaa,Ms.Mrae dt
888          Jhso,Ms.CteieHln"are
889                   Bh,M.Kr oel
890                    Doe,M.Ptik
Name: Name, Length: 891, dtype: object

In [59]:
## we can find the any number of character using the slicing in  the vectorized operation